spring:
  application:
    name: SmartContactManager
  datasource:
    username: root
    password: root@123
    url: jdbc:mysql://localhost:3306/smartcontact
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    enabled: true
server:
  port: 8082
logging:
  level:
    root: INFO