spring:
  application:
    name: SmartContactManager
  datasource:
    username: root
    password: root@123
    url: jdbc:mysql://localhost:3306/smartcontact
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update